//! Golden tests: compare candle-swin outputs against PyTorch reference.
//!
//! Test data generated by `scripts/generate_golden_data.py` which runs the
//! BiRefNet Swin V1 PyTorch implementation and saves inputs, weights, and
//! expected outputs as safetensors files.

use candle_core::{DType, Device, Result, Tensor, Var};
use candle_nn::{VarBuilder, VarMap};
use std::collections::HashMap;

fn load_test_case(name: &str) -> HashMap<String, Tensor> {
    let path = format!("test-data/{name}.safetensors");
    let data = std::fs::read(&path).unwrap_or_else(|_| panic!("missing test data: {path}"));
    let tensors = safetensors::SafeTensors::deserialize(&data).unwrap();
    let device = &Device::Cpu;

    tensors
        .tensors()
        .into_iter()
        .map(|(name, view)| {
            let dtype = match view.dtype() {
                safetensors::Dtype::F32 => DType::F32,
                safetensors::Dtype::F64 => DType::F64,
                safetensors::Dtype::I64 => DType::I64,
                safetensors::Dtype::U32 => DType::U32,
                dt => panic!("unsupported dtype {dt:?} for tensor {name}"),
            };
            let tensor = Tensor::from_raw_buffer(view.data(), dtype, view.shape(), device).unwrap();
            (name.to_string(), tensor)
        })
        .collect()
}

fn assert_tensor_close(actual: &Tensor, expected: &Tensor, atol: f64) {
    let diff = actual
        .to_dtype(DType::F64)
        .unwrap()
        .sub(&expected.to_dtype(DType::F64).unwrap())
        .unwrap()
        .abs()
        .unwrap()
        .flatten_all()
        .unwrap()
        .max(0)
        .unwrap()
        .to_scalar::<f64>()
        .unwrap();
    assert!(
        diff < atol,
        "max abs diff: {diff}, tolerance: {atol}\nactual shape: {:?}, expected shape: {:?}",
        actual.dims(),
        expected.dims()
    );
}

/// Build a VarBuilder from "param.*" entries in the test data.
/// The "param." prefix is stripped so keys match candle-nn's expected names.
fn vb_from_params(data: &HashMap<String, Tensor>) -> (VarMap, VarBuilder) {
    let varmap = VarMap::new();
    {
        let mut data_map = varmap.data().lock().unwrap();
        for (key, tensor) in data {
            if let Some(param_name) = key.strip_prefix("param.") {
                data_map.insert(param_name.to_string(), Var::from_tensor(tensor).unwrap());
            }
        }
    }
    let vb = VarBuilder::from_varmap(&varmap, DType::F32, &Device::Cpu);
    (varmap, vb)
}

// ============================================================================
// PatchEmbed
// ============================================================================

#[test]
fn golden_patch_embed() -> Result<()> {
    let data = load_test_case("patch_embed");
    let (_varmap, vb) = vb_from_params(&data);

    let pe = candle_swin::patch_embed::PatchEmbed::new(4, 3, 96, true, vb)?;
    let output = pe.forward(&data["input"])?;

    assert_eq!(output.dims(), data["output"].dims());
    assert_tensor_close(&output, &data["output"], 1e-4);
    Ok(())
}

// ============================================================================
// PatchMerging
// ============================================================================

#[test]
fn golden_patch_merging() -> Result<()> {
    let data = load_test_case("patch_merging");
    let (_varmap, vb) = vb_from_params(&data);

    let h: usize = data["H"].to_scalar::<i64>()? as usize;
    let w: usize = data["W"].to_scalar::<i64>()? as usize;

    let pm = candle_swin::patch_merging::PatchMerging::new(96, vb)?;
    let (output, new_h, new_w) = pm.forward(&data["input"], h, w)?;

    assert_eq!(new_h, h / 2);
    assert_eq!(new_w, w / 2);
    assert_eq!(output.dims(), data["output"].dims());
    assert_tensor_close(&output, &data["output"], 1e-4);
    Ok(())
}

// ============================================================================
// WindowAttention
// ============================================================================

#[test]
fn golden_window_attention_no_mask() -> Result<()> {
    let data = load_test_case("window_attention_no_mask");
    let (_varmap, vb) = vb_from_params(&data);

    let wa =
        candle_swin::window_attention::WindowAttention::new(96, (7, 7), 3, true, 0.0, 0.0, vb)?;
    let output = wa.forward(&data["input"], None)?;

    assert_eq!(output.dims(), data["output"].dims());
    assert_tensor_close(&output, &data["output"], 1e-4);
    Ok(())
}

#[test]
fn golden_window_attention_with_mask() -> Result<()> {
    let data = load_test_case("window_attention_with_mask");
    let (_varmap, vb) = vb_from_params(&data);

    let wa =
        candle_swin::window_attention::WindowAttention::new(96, (7, 7), 3, true, 0.0, 0.0, vb)?;
    let mask = &data["mask"];
    let output = wa.forward(&data["input"], Some(mask))?;

    assert_eq!(output.dims(), data["output"].dims());
    assert_tensor_close(&output, &data["output"], 1e-4);
    Ok(())
}

// ============================================================================
// SwinTransformerBlock
// ============================================================================

#[test]
fn golden_swin_block_no_shift() -> Result<()> {
    let data = load_test_case("swin_block_no_shift");
    let (_varmap, vb) = vb_from_params(&data);

    let h: usize = data["H"].to_scalar::<i64>()? as usize;
    let w: usize = data["W"].to_scalar::<i64>()? as usize;

    let block = candle_swin::swin_transformer_block::SwinTransformerBlock::new(
        96, 3, 7, 0, 4.0, true, 0.0, 0.0, vb,
    )?;
    let output = block.forward(&data["input"], h, w, None)?;

    assert_eq!(output.dims(), data["output"].dims());
    assert_tensor_close(&output, &data["output"], 1e-4);
    Ok(())
}

#[test]
fn golden_swin_block_shifted() -> Result<()> {
    let data = load_test_case("swin_block_shifted");
    let (_varmap, vb) = vb_from_params(&data);

    let h: usize = data["H"].to_scalar::<i64>()? as usize;
    let w: usize = data["W"].to_scalar::<i64>()? as usize;

    let ws: usize = 7;
    let shift: usize = ws / 2;
    let block = candle_swin::swin_transformer_block::SwinTransformerBlock::new(
        96, 3, ws, shift, 4.0, true, 0.0, 0.0, vb,
    )?;

    let attn_mask = &data["attn_mask"];
    let output = block.forward(&data["input"], h, w, Some(attn_mask))?;

    assert_eq!(output.dims(), data["output"].dims());
    assert_tensor_close(&output, &data["output"], 1e-4);
    Ok(())
}

// ============================================================================
// Full SwinTransformer
// ============================================================================

#[test]
fn golden_swin_tiny_full() -> Result<()> {
    let data = load_test_case("swin_tiny_full");
    let (_varmap, vb) = vb_from_params(&data);

    let config = candle_swin::swin_transformer::SwinTransformerConfig {
        patch_size: 4,
        in_channels: 3,
        embed_dim: 96,
        depths: vec![2, 2, 2, 2], // Reduced depths matching test data
        num_heads: vec![3, 6, 12, 24],
        window_size: 7,
        mlp_ratio: 4.0,
        qkv_bias: true,
        drop_rate: 0.0,
        attn_drop_rate: 0.0,
        out_indices: vec![0, 1, 2, 3],
    };
    let model = candle_swin::SwinTransformer::new(&config, vb)?;
    let outputs = model.forward(&data["input"])?;

    assert_eq!(outputs.len(), 4);
    for i in 0..4 {
        let key = format!("output_{i}");
        let expected = &data[&key];
        assert_eq!(
            outputs[i].dims(),
            expected.dims(),
            "shape mismatch at stage {i}"
        );
        assert_tensor_close(&outputs[i], expected, 1e-3);
    }
    Ok(())
}

// ============================================================================
// BiRefNet pretrained Swin-L backbone
// ============================================================================

/// End-to-end test using BiRefNet's pretrained Swin-Large backbone weights.
///
/// Loads the official BiRefNet model's backbone (swin_v1_l) with real pretrained
/// weights (fp16 -> fp32), feeds a 384x384 input, and compares all 4 stage
/// outputs against PyTorch reference within 1e-2 tolerance.
///
/// This validates that the candle-swin implementation is numerically compatible
/// with the PyTorch Swin V1 used in BiRefNet production inference.
#[test]
fn golden_birefnet_swin_backbone() -> Result<()> {
    let data = load_test_case("birefnet_swin_backbone");
    let (_varmap, vb) = vb_from_params(&data);

    let config = candle_swin::swin_transformer::SwinTransformerConfig::large();
    let model = candle_swin::SwinTransformer::new(&config, vb)?;
    let outputs = model.forward(&data["input"])?;

    assert_eq!(outputs.len(), 4);

    let expected_shapes: [(usize, usize, usize, usize); 4] = [
        (1, 192, 96, 96),
        (1, 384, 48, 48),
        (1, 768, 24, 24),
        (1, 1536, 12, 12),
    ];

    for i in 0..4 {
        let key = format!("output_{i}");
        let expected = &data[&key];

        assert_eq!(
            outputs[i].dims4()?,
            expected_shapes[i],
            "shape mismatch at stage {i}"
        );
        assert_eq!(
            outputs[i].dims(),
            expected.dims(),
            "shape mismatch at stage {i}"
        );

        // Actual max error is ~1.85e-4 (fp32 rounding across deep network)
        assert_tensor_close(&outputs[i], expected, 1e-3);
    }
    Ok(())
}
